/**
 * Build all blocks using @wordpress/scripts (no custom webpack).
 * 1) Main build per block: src/index.js → build/index.js, build/style-index.css, build/index.asset.php
 * 2) For blocks with src/view.js: second build → build/view.js, build/view.asset.php (via temp dir)
 */
const path = require('path');
const fs = require('fs');
const { spawnSync } = require('child_process');

const pluginDir = path.resolve(__dirname, '..');
const blocksDir = path.join(pluginDir, 'blocks');
const tempViewDir = path.join(pluginDir, '.temp-view-build');

function runWpScripts(webpackSrcDir, outputPath) {
	const srcArg = path.relative(pluginDir, webpackSrcDir).replace(/\\/g, '/');
	const outArg = path.relative(pluginDir, outputPath).replace(/\\/g, '/');
	return spawnSync(
		'npx',
		['wp-scripts', 'build', `--webpack-src-dir=${srcArg}`, `--output-path=${outArg}`],
		{ cwd: pluginDir, stdio: 'inherit', shell: true }
	);
}

const blockSlugs = fs.readdirSync(blocksDir).filter((name) => {
	const dir = path.join(blocksDir, name);
	return (
		fs.statSync(dir).isDirectory() &&
		fs.existsSync(path.join(dir, 'src', 'index.js'))
	);
});

if (blockSlugs.length === 0) {
	console.warn('No blocks found with src/index.js');
	process.exit(0);
}

let failed = false;

for (const slug of blockSlugs) {
	const srcDir = path.join(blocksDir, slug, 'src');
	const outDir = path.join(blocksDir, slug, 'build');
	console.log(`Building block: ${slug}...`);
	const result = runWpScripts(srcDir, outDir);
	if (result.status !== 0) failed = true;

	// If block has src/view.js, build it so build/view.js and build/view.asset.php are generated by wp-scripts
	const viewSrc = path.join(blocksDir, slug, 'src', 'view.js');
	if (fs.existsSync(viewSrc)) {
		try {
			if (!fs.existsSync(tempViewDir)) fs.mkdirSync(tempViewDir, { recursive: true });
			const tempIndex = path.join(tempViewDir, 'index.js');
			fs.copyFileSync(viewSrc, tempIndex);
			const tempOut = path.join(pluginDir, '.temp-view-out');
			if (fs.existsSync(tempOut)) {
				fs.rmSync(tempOut, { recursive: true });
			}
			fs.mkdirSync(tempOut, { recursive: true });
			const res = runWpScripts(tempViewDir, tempOut);
			if (res.status !== 0) {
				failed = true;
			} else {
				const outBuild = path.join(blocksDir, slug, 'build');
				if (!fs.existsSync(outBuild)) fs.mkdirSync(outBuild, { recursive: true });
				fs.renameSync(path.join(tempOut, 'index.js'), path.join(outBuild, 'view.js'));
				if (fs.existsSync(path.join(tempOut, 'index.asset.php'))) {
					fs.renameSync(path.join(tempOut, 'index.asset.php'), path.join(outBuild, 'view.asset.php'));
				}
			}
			if (fs.existsSync(tempOut)) fs.rmSync(tempOut, { recursive: true });
		} finally {
			if (fs.existsSync(tempViewDir)) fs.rmSync(tempViewDir, { recursive: true });
		}
	}
}

process.exit(failed ? 1 : 0);
